name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run vulnerability scan
        run: |
          python main.py --scan-target <TARGET_URL>  # Replace <TARGET_URL> with the actual target URL

      - name: Upload scan results
        uses: actions/upload-artifact@v2
        with:
          name: scan-results
          path: reports/
